# -*- coding: utf-8 -*-
"""Clase de Solucion IMDB Análisis Sentimientos RNN.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cWOOrOlsv6z4ta4jo8MfcLFhEO0fNMaJ

# Análisis de Sentimientos de Reviews de Películas en IMDB

Vamos a trabajar en un proyecto de NLP muy común, como es el análisis de sentimientos.

En este caso, vamos a utilizar datos recopilados de reviews de películas de la empresa IMDB.

Estos datos se pueden obtener desde https://ai.stanford.edu/~amaas/data/sentiment/ aunque nosotros los vamos a importar directamente desde el paquete datasets de Keras.

**Importamos las librerías necesarias**
"""

from keras.datasets import imdb
from keras.utils import pad_sequences
from keras.models import Sequential
from keras.layers import Embedding, LSTM, GRU, SimpleRNN,  Dense
import numpy as np

"""Cargamos el dataset de "IMDB review sentiment classification" y los procesamos para utilizar solo las 10000 palabras más comunes."""

# Cargamos el dataset de IMDB, pero solo utilizaremos las 10000 palabras más comunes
(x_train, y_train), (x_test, y_test) = imdb.load_data(num_words=10000)

"""Exploramos los datos"""

data = np.concatenate((x_train, x_test), axis=0)
targets = np.concatenate((y_train, y_test), axis=0)

print("Categories:", np.unique(targets))
print("Number of unique words:", len(np.unique(np.hstack(data))))

length = [len(i) for i in data]
print("Average Review length:", np.mean(length))
print("Standard Deviation:", round(np.std(length)))

unique_elements, counts_elements = np.unique(targets, return_counts=True)
print("Frequency of unique values of the said array:")
print(np.asarray((unique_elements, counts_elements)))

"""Limitamos la longitud de cada review a 500 palabras para hacer este caso más rápido."""

# Limitamos la longitud de cada review a 500 palabras
max_words = 500
x_train = pad_sequences(x_train, maxlen=max_words)
x_test = pad_sequences(x_test, maxlen=max_words)

"""A continuación, se crea una RNN utilizando la** clase Sequential** de Keras.

El modelo consta de una **capa de incrustación (Embedding)** para poder tokenizar las palabras y para aprender los vectores de las palabras de entrada, una **capa LSTM** para aprender las dependencias temporales y una **capa densa de salida** con una unidad y **activación sigmoid** para la **clasificación binaria**.
"""

# Creamos el modelo de la RNN
model = Sequential()

# Añadimos la capa de incrustación para tokenizar, con un tamaño de vectores de 32
model.add(Embedding(10000, 32))

# Capa SimpleRNN, de tamaño 32
model.add(SimpleRNN(32))
# Si queremos hacerlo con la capa LSTM con una memoria de 100 unidades
# model.add(LSTM(100))
# Si queremos hacerlo con una capa SimpleRNN con una memoria de 100 unidades
# model.add(GRU(100))

# Añadimos la capa densa de salida con una sola unidad y activación sigmoid
model.add(Dense(1, activation='sigmoid'))

"""Obtenemos un resumen del modelo"""

model.summary()

"""Finalmente, el modelo es compilado, entrenado y evaluado en el conjunto de test."""

# Compilamos el modelo
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['acc'])

# Entrenamos el modelo
history = model.fit(x_train, y_train,
                    epochs=6,
                    batch_size=128,
                    validation_split=0.2)

"""Visualizamos el entrenamiento"""

import matplotlib.pyplot as plt

acc = history.history['acc']
val_acc = history.history['val_acc']
loss = history.history['loss']
val_loss = history.history['val_loss']

epochs = range(1, len(acc) + 1)

plt.plot(epochs, acc, 'bo', label='Training acc')
plt.plot(epochs, val_acc, 'b', label='Validation acc')
plt.title('Training and validation accuracy')
plt.legend()

plt.figure()

plt.plot(epochs, loss, 'bo', label='Training loss')
plt.plot(epochs, val_loss, 'b', label='Validation loss')
plt.title('Training and validation loss')
plt.legend()

plt.show()

# Evaluamos el modelo en el conjunto de test
score, acc = model.evaluate(x_test, y_test, batch_size=64)
print('Score: %.2f' % (score))
print('Accuracy: %.2f' % (acc))

"""# Capa LSTM"""

from keras.layers import LSTM

# construir modelo con Embedding + LSTM
model = Sequential()
model.add(Embedding(10000, 32))
model.add(LSTM(32))
model.add(Dense(1, activation='sigmoid'))

# compilar modelo
model.compile(optimizer='rmsprop',
              loss='binary_crossentropy',
              metrics=['acc'])
# entrenar modelo
history = model.fit(x_train, y_train,
                    epochs=10,
                    batch_size=128,
                    validation_split=0.2)

import matplotlib.pyplot as plt

acc = history.history['acc']
val_acc = history.history['val_acc']
loss = history.history['loss']
val_loss = history.history['val_loss']

epochs = range(1, len(acc) + 1)

plt.plot(epochs, acc, 'bo', label='Training acc')
plt.plot(epochs, val_acc, 'b', label='Validation acc')
plt.title('Training and validation accuracy')
plt.legend()

plt.figure()

plt.plot(epochs, loss, 'bo', label='Training loss')
plt.plot(epochs, val_loss, 'b', label='Validation loss')
plt.title('Training and validation loss')
plt.legend()

plt.show()

# Evaluamos el modelo en el conjunto de test
score, acc = model.evaluate(x_test, y_test, batch_size=64)
print('Score: %.2f' % (score))
print('Accuracy: %.2f' % (acc))

"""# Capa GRU"""

from keras.layers import LSTM

# construir modelo con Embedding + LSTM
model = Sequential()
model.add(Embedding(10000, 32))
model.add(GRU(32))
model.add(Dense(1, activation='sigmoid'))

# compilar modelo
model.compile(optimizer='rmsprop',
              loss='binary_crossentropy',
              metrics=['acc'])
# entrenar modelo
history = model.fit(x_train, y_train,
                    epochs=10,
                    batch_size=128,
                    validation_split=0.2)

import matplotlib.pyplot as plt

acc = history.history['acc']
val_acc = history.history['val_acc']
loss = history.history['loss']
val_loss = history.history['val_loss']

epochs = range(1, len(acc) + 1)

plt.plot(epochs, acc, 'bo', label='Training acc')
plt.plot(epochs, val_acc, 'b', label='Validation acc')
plt.title('Training and validation accuracy')
plt.legend()

plt.figure()

plt.plot(epochs, loss, 'bo', label='Training loss')
plt.plot(epochs, val_loss, 'b', label='Validation loss')
plt.title('Training and validation loss')
plt.legend()

plt.show()

# Evaluamos el modelo en el conjunto de test
score, acc = model.evaluate(x_test, y_test, batch_size=64)
print('Score: %.2f' % (score))
print('Accuracy: %.2f' % (acc))